# Generated by Django 2.2.4 on 2024-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authorandBooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='notes',
            new_name='Notes',
        ),
    ]
